// https://leetcode.com/problems/bulb-switcher/submissions/

// Fastest possible solution. Figured it out by identifying the pattern.
// The number of bulbs that are on increase at n = (1, 4, 9, 16, 25, 36 ...)
// That's a series generated by f(x) =  2*f(x - 1) - f(x - 2) + 2
// Where f(0) = 0, f(1) = 1

class Solution {
public:
    int bulbSwitch(int n) {
        int ans = 0, count = 1, x = 1;
        while(n >= count){
            ++ans;
            x += 2;
            count += x;
        }
        return ans;
    }
};